=== BrylSerhii/laba_2/src/main/resources/xsd/tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Tariffs" type="TariffsType"/>

    <xs:complexType name="TariffsType">
        <xs:sequence>
            <xs:element name="Tariff" type="TariffType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TariffType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="OperatorName" type="xs:string"/>
            <xs:element name="Payroll" type="PayrollType"/>
            <xs:element name="CallPrices" type="CallPricesType"/>
            <xs:element name="SMSPrice" type="PayrollType"/>
            <xs:element name="Parameters" type="ParametersType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PayrollType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="currency" type="xs:string" use="optional" fixed="UAH"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="CallPricesType">
        <xs:sequence>
            <xs:element name="InsideNetwork" type="PayrollType" minOccurs="0"/>
            <xs:element name="OutsideNetwork" type="PayrollType" minOccurs="0"/>
            <xs:element name="Landline" type="PayrollType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ParametersType">
        <xs:sequence>
            <xs:element name="FavoriteNumber" type="xs:integer" minOccurs="0"/>
            <xs:element name="Tariffing" type="TariffingType"/>
            <xs:element name="ConnectionFee" type="PayrollType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TariffingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="12-second"/>
            <xs:enumeration value="per-minute"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== BrylSerhii/laba_2/target/classes/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/tariff.xsd">
    <Tariff>
        <Name>SuperTariff</Name>
        <OperatorName>Мобільний Оператор A</OperatorName>
        <Payroll currency="UAH">250.00</Payroll>
        <CallPrices>
            <InsideNetwork currency="UAH">1.50</InsideNetwork>
            <OutsideNetwork currency="UAH">2.00</OutsideNetwork>
            <Landline currency="UAH">3.00</Landline>
        </CallPrices>
        <SMSPrice currency="UAH">0.75</SMSPrice>
        <Parameters>
            <FavoriteNumber>3</FavoriteNumber>
            <Tariffing>12-second</Tariffing>
            <ConnectionFee currency="UAH">50.00</ConnectionFee>
        </Parameters>
    </Tariff>

    <Tariff>
        <Name>EcoTariff</Name>
        <OperatorName>Мобільний Оператор B</OperatorName>
        <Payroll currency="UAH">150.00</Payroll>
        <CallPrices>
            <InsideNetwork currency="UAH">1.00</InsideNetwork>
            <OutsideNetwork currency="UAH">1.80</OutsideNetwork>
            <Landline currency="UAH">2.50</Landline>
        </CallPrices>
        <SMSPrice currency="UAH">0.60</SMSPrice>
        <Parameters>
            <FavoriteNumber>5</FavoriteNumber>
            <Tariffing>per-minute</Tariffing>
            <ConnectionFee currency="UAH">30.00</ConnectionFee>
        </Parameters>
    </Tariff>

    <Tariff>
        <Name>BusinessTariff</Name>
        <OperatorName>Мобільний Оператор C</OperatorName>
        <Payroll currency="UAH">500.00</Payroll>
        <CallPrices>
            <InsideNetwork currency="UAH">1.20</InsideNetwork>
            <OutsideNetwork currency="UAH">2.50</OutsideNetwork>
            <Landline currency="UAH">3.20</Landline>
        </CallPrices>
        <SMSPrice currency="UAH">0.80</SMSPrice>
        <Parameters>
            <FavoriteNumber>2</FavoriteNumber>
            <Tariffing>12-second</Tariffing>
            <ConnectionFee currency="UAH">100.00</ConnectionFee>
        </Parameters>
    </Tariff>
</Tariffs>
